/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asana_assistant_2.view;

import asana_assistant_1.control.ControlException;
import asana_assistant_1.control.IRouter;
import asana_assistant_1.control.dtos.DevelopmentDTO;
import asana_assistant_1.model.Task;
import asana_assistant_1.view.View;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JFormattedTextField;
import javax.swing.JSpinner;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author Gabriel
 */
class AddDevelopmentDialog extends javax.swing.JDialog {
    private UserFrame parent;
    private IRouter router;
    private Task task;
    private DefaultListModel evidenceListModel;
    
    public AddDevelopmentDialog(View source, UserFrame parent, Task task, Date date) {
        super(parent, true);
        initComponents();
        this.setLocationRelativeTo(parent);
        this.setIconImage(parent.getIconImage());
        this.setTitle("New Development");
        
        this.parent = parent;
        this.router = source.getRouter();
        this.task = task;
        
        this.evidenceListModel = new DefaultListModel();
        this.EvidenceList.setModel(evidenceListModel);
        this.DateChooser.setDate(date);
        this.DateChooser.getDateEditor().setEnabled(false);
        JFormattedTextField hoursTextField = ((JSpinner.NumberEditor)this.HoursSpinner.getEditor()).getTextField();
        ((NumberFormatter)hoursTextField.getFormatter()).setAllowsInvalid(false);
    }
    private void addEvidence(){
        JFileChooser chooser  = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        if(chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
        {
            String filename = chooser.getSelectedFile().getAbsolutePath();
            evidenceListModel.addElement(filename);
        }
    }
    private void removeEvidence(){
        String string = EvidenceList.getSelectedValue();
        if(string == null)
            NewView.displayError(this, "You must select an evidence entry to remove.");
        else
            evidenceListModel.removeElement(string);
    }
    private void addDevelopment(){
        try{
            if(NewView.displayConfirm(this, "Adding a development is non-reversible.\nDo you want to save your changes?")){
                LocalDate date = DateChooser.getDate()
                        .toInstant()
                        .atZone(ZoneId.systemDefault())
                        .toLocalDate();
                int hours = (Integer)HoursSpinner.getValue();
                String description = DescriptionTextArea.getText();
                ArrayList<String> evidence = new ArrayList();
                for(Object evidence_ : evidenceListModel.toArray())
                    evidence.add((String)evidence_);
                DevelopmentDTO development = new DevelopmentDTO(date, hours, description, evidence);
                router.addDevelopment(task.getId(), development);
                NewView.displayInfo(this, "Development added successfully.");
                //parent.resetDevelopmentFilters();
                this.dispose();
            }
        } catch(ControlException ex) {
            NewView.displayError(this, ex);
        }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ProjectNameLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        DateChooser = new com.toedter.calendar.JDateChooser();
        ProjectNameLabel2 = new javax.swing.JLabel();
        HoursSpinner = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        DescriptionTextArea = new javax.swing.JTextArea();
        ProjectNameLabel3 = new javax.swing.JLabel();
        ProjectNameLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        EvidenceList = new javax.swing.JList<>();
        AddButton = new javax.swing.JButton();
        RemoveButton = new javax.swing.JButton();
        AddDevelopmentButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        ProjectNameLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(85, 96, 115));

        ProjectNameLabel1.setFont(new java.awt.Font("Proxima Nova Rg", 0, 14)); // NOI18N
        ProjectNameLabel1.setForeground(new java.awt.Color(255, 255, 255));
        ProjectNameLabel1.setText("Date:");

        DateChooser.setForeground(new java.awt.Color(85, 96, 115));

        ProjectNameLabel2.setFont(new java.awt.Font("Proxima Nova Rg", 0, 14)); // NOI18N
        ProjectNameLabel2.setForeground(new java.awt.Color(255, 255, 255));
        ProjectNameLabel2.setText("Hours Of Work: ");

        HoursSpinner.setFont(new java.awt.Font("Proxima Nova Rg", 0, 13)); // NOI18N

        DescriptionTextArea.setColumns(20);
        DescriptionTextArea.setFont(new java.awt.Font("Proxima Nova Rg", 0, 14)); // NOI18N
        DescriptionTextArea.setForeground(new java.awt.Color(29, 38, 52));
        DescriptionTextArea.setRows(5);
        jScrollPane1.setViewportView(DescriptionTextArea);

        ProjectNameLabel3.setFont(new java.awt.Font("Proxima Nova Rg", 0, 14)); // NOI18N
        ProjectNameLabel3.setForeground(new java.awt.Color(255, 255, 255));
        ProjectNameLabel3.setText("Description: ");

        ProjectNameLabel4.setFont(new java.awt.Font("Proxima Nova Rg", 0, 14)); // NOI18N
        ProjectNameLabel4.setForeground(new java.awt.Color(255, 255, 255));
        ProjectNameLabel4.setText("Evidence:");

        EvidenceList.setFont(new java.awt.Font("Proxima Nova Rg", 0, 14)); // NOI18N
        EvidenceList.setForeground(new java.awt.Color(29, 38, 52));
        EvidenceList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        EvidenceList.setSelectionBackground(new java.awt.Color(255, 102, 0));
        EvidenceList.setSelectionForeground(new java.awt.Color(243, 242, 242));
        jScrollPane2.setViewportView(EvidenceList);

        AddButton.setBackground(new java.awt.Color(85, 96, 115));
        AddButton.setFont(new java.awt.Font("Proxima Nova Rg", 0, 16)); // NOI18N
        AddButton.setForeground(new java.awt.Color(255, 255, 255));
        AddButton.setText("Add");
        AddButton.setBorder(null);
        AddButton.setBorderPainted(false);
        AddButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AddButton.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        AddButton.setFocusPainted(false);
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        RemoveButton.setBackground(new java.awt.Color(85, 96, 115));
        RemoveButton.setFont(new java.awt.Font("Proxima Nova Rg", 0, 16)); // NOI18N
        RemoveButton.setForeground(new java.awt.Color(255, 255, 255));
        RemoveButton.setText("Remove");
        RemoveButton.setBorder(null);
        RemoveButton.setBorderPainted(false);
        RemoveButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        RemoveButton.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        RemoveButton.setFocusPainted(false);
        RemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveButtonActionPerformed(evt);
            }
        });

        AddDevelopmentButton.setBackground(new java.awt.Color(255, 102, 0));
        AddDevelopmentButton.setFont(new java.awt.Font("Proxima Nova Rg", 0, 16)); // NOI18N
        AddDevelopmentButton.setForeground(new java.awt.Color(255, 255, 255));
        AddDevelopmentButton.setText("Add Develpment");
        AddDevelopmentButton.setBorder(null);
        AddDevelopmentButton.setBorderPainted(false);
        AddDevelopmentButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AddDevelopmentButton.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        AddDevelopmentButton.setFocusPainted(false);
        AddDevelopmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDevelopmentButtonActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(29, 38, 52));

        ProjectNameLabel.setFont(new java.awt.Font("Proxima Nova Rg", 0, 20)); // NOI18N
        ProjectNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        ProjectNameLabel.setText("Development Info");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ProjectNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(ProjectNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ProjectNameLabel2)
                                .addGap(27, 27, 27)
                                .addComponent(HoursSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ProjectNameLabel1)
                                .addGap(31, 31, 31)
                                .addComponent(DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ProjectNameLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(AddDevelopmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ProjectNameLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(RemoveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(33, Short.MAX_VALUE))))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProjectNameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HoursSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProjectNameLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProjectNameLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProjectNameLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RemoveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(AddDevelopmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        addEvidence();
    }//GEN-LAST:event_AddButtonActionPerformed

    private void RemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveButtonActionPerformed
        removeEvidence();
    }//GEN-LAST:event_RemoveButtonActionPerformed

    private void AddDevelopmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDevelopmentButtonActionPerformed
        addDevelopment();
    }//GEN-LAST:event_AddDevelopmentButtonActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton AddDevelopmentButton;
    private com.toedter.calendar.JDateChooser DateChooser;
    private javax.swing.JTextArea DescriptionTextArea;
    private javax.swing.JList<String> EvidenceList;
    private javax.swing.JSpinner HoursSpinner;
    private javax.swing.JLabel ProjectNameLabel;
    private javax.swing.JLabel ProjectNameLabel1;
    private javax.swing.JLabel ProjectNameLabel2;
    private javax.swing.JLabel ProjectNameLabel3;
    private javax.swing.JLabel ProjectNameLabel4;
    private javax.swing.JButton RemoveButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
