/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asana_assistant_2.view;

import asana_assistant_1.control.ControlException;
import asana_assistant_1.control.IRouter;
import asana_assistant_1.control.dtos.DisplayString;
import asana_assistant_1.model.User;
import asana_assistant_1.view.View;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author Gabriel
 */
public class ProjectDialog extends javax.swing.JDialog {

    private UserFrame parent;
    private IRouter router;
    private View source;
    private User user;
    
    private final DefaultListModel managedListModel;
    private final DefaultListModel collaborateListModel;
    
    public ProjectDialog(View source, UserFrame parent,User user) {
        super(parent, true);
        initComponents();
        this.setLocationRelativeTo(parent);
        this.setIconImage(parent.getIconImage());
        this.parent = parent;
        this.source = source;
        this.router = source.getRouter();
        this.user = user;
        this.managedListModel = new DefaultListModel();
        this.collaborateListModel = new DefaultListModel();
        this.setTitle(user.getName() + " - " + user.getEmail());
        this.ManagedList.setModel(managedListModel);
        this.CollaborateList.setModel(collaborateListModel);
        reloadManagedList();
        reloadCollaborateList();
    }
    
    public void reloadManagedList(){
        try{
            List<DisplayString> strings = router.getAdminProjectStrings(user.getId());
            managedListModel.clear();
            for(DisplayString string : strings)
                managedListModel.addElement(string);
        } catch(ControlException ex) {
            NewView.displayError(this, ex);
        }
    }
    
    public void reloadCollaborateList(){
        try{
            List<DisplayString> strings = router.getCollabProjectStrings(user.getId());
            collaborateListModel.clear();
            for(DisplayString string : strings)
                collaborateListModel.addElement(string);
        } catch(ControlException ex) {
            NewView.displayError(this, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundPanel = new javax.swing.JPanel();
        ProjectsLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        ProjectsTabbedPane = new javax.swing.JTabbedPane();
        ManageScrollPane = new javax.swing.JScrollPane();
        ManagedList = new javax.swing.JList<>();
        CollaborateScrollPane = new javax.swing.JScrollPane();
        CollaborateList = new javax.swing.JList<>();
        AddProjectButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        BackgroundPanel.setBackground(new java.awt.Color(29, 38, 52));

        ProjectsLabel.setFont(new java.awt.Font("Proxima Nova Rg", 0, 20)); // NOI18N
        ProjectsLabel.setForeground(new java.awt.Color(255, 255, 255));
        ProjectsLabel.setText("Projects");

        javax.swing.GroupLayout BackgroundPanelLayout = new javax.swing.GroupLayout(BackgroundPanel);
        BackgroundPanel.setLayout(BackgroundPanelLayout);
        BackgroundPanelLayout.setHorizontalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(ProjectsLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BackgroundPanelLayout.setVerticalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(ProjectsLabel)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(85, 96, 115));

        ProjectsTabbedPane.setForeground(new java.awt.Color(29, 38, 52));
        ProjectsTabbedPane.setFont(new java.awt.Font("Proxima Nova Rg", 1, 14)); // NOI18N

        ManageScrollPane.setBorder(null);

        ManagedList.setFont(new java.awt.Font("Proxima Nova Rg", 0, 14)); // NOI18N
        ManagedList.setForeground(new java.awt.Color(85, 96, 115));
        ManagedList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ManageScrollPane.setViewportView(ManagedList);

        ProjectsTabbedPane.addTab("Manage", ManageScrollPane);

        CollaborateScrollPane.setBorder(null);

        CollaborateList.setFont(new java.awt.Font("Proxima Nova Rg", 0, 14)); // NOI18N
        CollaborateList.setForeground(new java.awt.Color(85, 96, 115));
        CollaborateList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        CollaborateScrollPane.setViewportView(CollaborateList);

        ProjectsTabbedPane.addTab("Collaborate", CollaborateScrollPane);

        AddProjectButton.setBackground(new java.awt.Color(255, 102, 0));
        AddProjectButton.setFont(new java.awt.Font("Proxima Nova Rg", 0, 16)); // NOI18N
        AddProjectButton.setForeground(new java.awt.Color(255, 255, 255));
        AddProjectButton.setText("Add Project");
        AddProjectButton.setBorder(null);
        AddProjectButton.setBorderPainted(false);
        AddProjectButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AddProjectButton.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        AddProjectButton.setFocusPainted(false);
        AddProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProjectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProjectsTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddProjectButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProjectsTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AddProjectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        ProjectsTabbedPane.getAccessibleContext().setAccessibleName("Manage");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProjectButtonActionPerformed
        new AddProjectDialog(source,this,user).setVisible(true);
    }//GEN-LAST:event_AddProjectButtonActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddProjectButton;
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JList<String> CollaborateList;
    private javax.swing.JScrollPane CollaborateScrollPane;
    private javax.swing.JScrollPane ManageScrollPane;
    private javax.swing.JList<String> ManagedList;
    private javax.swing.JLabel ProjectsLabel;
    private javax.swing.JTabbedPane ProjectsTabbedPane;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
